
name: Build/TNC
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt install portaudio19-dev
          python -m pip install --upgrade pip
          pip3 install pyaudio
          pip3 install psutil
          pip3 install crcengine
          pip3 install pyinstaller
      - name: Build with Pyinstaller
        run: |
          pyinstaller -F daemon.py -n daemon
          pyinstaller -F main.py -n tnc
