
name: Build/TNC
on: push

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt install portaudio19-dev
          python -m pip install --upgrade pip
          pip3 install pyaudio
          pip3 install psutil
          pip3 install crcengine
          pip3 install pyinstaller
      - name: Build with Pyinstaller
        working-directory: tnc
        run: |      
          pyinstaller -F daemon.py -n daemon
          pyinstaller -F main.py -n tnc
          cd dist
          ls -R
      
      - name: Save build artifacts to Action
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-latest
          path: ./tnc/dist/
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn` 
     
      - name: Save build artifacts to Repository
        uses: actions/download-artifact@v2
        with:
          name: daemon
          path: ./tnc/dist/
